from __future__ import annotations

import os
import shlex
from pathlib import Path

from rich.filesize import decimal

from .model import Node, ScanResult


def _iter_nodes(root: Node) -> "list[Node]":
    out: list[Node] = []
    stack = [root]
    while stack:
        node = stack.pop()
        out.append(node)
        # preserve pre-order by pushing reversed
        for child in reversed(node.children):
            stack.append(child)
    return out


def generate_delete_script(*, scan: ScanResult, selected_ids: set[int], output_path: Path) -> None:
    """Write a bash script with `rm -rf -- ...` lines for selected nodes."""

    id_to_node: dict[int, Node] = {}
    for n in _iter_nodes(scan.root):
        if n.node_id is not None:
            id_to_node[n.node_id] = n

    lines: list[str] = []
    lines.append("#!/usr/bin/env bash")
    lines.append("set -euo pipefail")
    lines.append("")
    lines.append("# Generated by diskspace-digger")
    lines.append("# Review carefully before running.")
    lines.append("")

    for node_id in sorted(selected_ids):
        node = id_to_node.get(node_id)
        if node is None:
            # Ignore unknown IDs (should be validated earlier).
            continue
        p = str(node.path)
        lines.append(f"# [{node_id}] {decimal(node.size_bytes)} {p}")
        lines.append(f"rm -rf -- {shlex.quote(p)}")
        lines.append("")

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(output_path, 0o755)
